### PR TITLE
feat: add new authentication feature at `README.md`

### PR DESCRIPTION
**Pull request by luannzin**

### CODE REVIEW

**Review by gelzinn — CHANGES_REQUESTED** [review]
change the authentication downwards to follow this pattern:

**database**
- x
- x
- x

**features**
- x

or something like that. what do you think?

**Comment by luannzin** [comment]
i think that should work, i'll do this as soon as possible

**Comment by luannzin** [comment]
could you review now? @gelzinn

**Comment by gelzinn** [comment]
a new version of the readme has been implemented, can you check it out?

**Pull request closed without merging**
